CREATE EXTENSION IF NOT EXISTS "pgcrypto";--> statement-breakpoint
CREATE TYPE "public"."job_status" AS ENUM('running', 'success', 'failed');--> statement-breakpoint
CREATE TYPE "public"."job_type" AS ENUM('process_all_shops', 'sync_content_shops', 'get_combined_pdf_lists', 'get_waiting_orders_pdf');--> statement-breakpoint
CREATE TYPE "public"."sync_status" AS ENUM('idle', 'running', 'success', 'failed');--> statement-breakpoint
CREATE TABLE "job_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"job_type" "job_type" NOT NULL,
	"status" "job_status" DEFAULT 'running' NOT NULL,
	"shop_id" uuid,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"details" jsonb,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "product_cards" (
	"shop_id" uuid NOT NULL,
	"nm_id" bigint NOT NULL,
	"vendor_code" text,
	"brand" text,
	"title" text,
	"img" text,
	"age_group" text,
	"wb_created_at" timestamp with time zone,
	"wb_updated_at" timestamp with time zone,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_cards_shop_id_nm_id_pk" PRIMARY KEY("shop_id","nm_id")
);
--> statement-breakpoint
CREATE TABLE "shops" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"wb_token" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"supply_prefix" text DEFAULT 'игрушки_' NOT NULL,
	"token_updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "shops_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "sync_state" (
	"shop_id" uuid PRIMARY KEY NOT NULL,
	"cursor_updated_at" timestamp with time zone,
	"cursor_nm_id" bigint,
	"last_synced_at" timestamp with time zone,
	"last_status" "sync_status" DEFAULT 'idle' NOT NULL,
	"last_error" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "job_runs" ADD CONSTRAINT "job_runs_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_cards" ADD CONSTRAINT "product_cards_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_state" ADD CONSTRAINT "sync_state_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "job_runs_job_type_started_idx" ON "job_runs" USING btree ("job_type","started_at");--> statement-breakpoint
CREATE INDEX "job_runs_status_started_idx" ON "job_runs" USING btree ("status","started_at");--> statement-breakpoint
CREATE INDEX "product_cards_shop_wb_updated_idx" ON "product_cards" USING btree ("shop_id","wb_updated_at");
